Meteor.subscribe 'drivers'
Meteor.subscribe 'companies'
Meteor.subscribe 'fleets'
Meteor.subscribe 'vehicles'
Meteor.subscribe 'countries'
Meteor.subscribe 'locations'
Meteor.subscribe 'expensesFuel'
Meteor.subscribe 'notifications'

Session.setDefault 'filterNotifications', ''
Session.setDefault 'filterFleets', ''
Session.setDefault 'filterVehicles', ''
Session.setDefault 'filterDrivers', ''
Session.setDefault 'activeCategory', 'dashboard'
