@DriverVehicleAssignments = new Mongo.Collection 'driverVehicleAssignments'
Partitioner.partitionCollection DriverVehicleAssignments
DriverVehicleAssignments.attachSchema Schema.driverVehicleAssignments
