web:
  image: greyarch/fleetr
  restart: unless-stopped
  extra_hosts:
   - "traccar:192.168.40.50"
  ports:
   - "80:80"
  environment:
   - ROOT_URL=http://fleetr.eu
   - MONGO_URL=mongodb://traccar:27017/admin
   - MONGO_OPLOG_URL=mongodb://traccar:27017/local?authSource=admin
   - 'METEOR_SETTINGS={"mqttUrl" : "mqtt://traccar:10028", "mqttClientId": "fleetr@prod"}'

logspout:
  image: ictu/logspout
  restart: unless-stopped
  hostname: logspout
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  extra_hosts:
    - "elk:192.168.40.70"
  environment:
    ROUTE_URIS: logstash://elk:5454
