web:
  image: greyarch/fleetr
  restart: unless-stopped
  ports:
   - "80:80"
  environment:
   - ROOT_URL=http://fleetr.eu
   - MONGO_URL=mongodb://traccar:27017/admin
   - MONGO_OPLOG_URL=mongodb://traccar:27017/local?authSource=admin
   - 'METEOR_SETTINGS={"mqttUrl" : "mqtt://traccar:10028"}'
